Proyecto2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () 
{
    return view('login');
});

Route::get('usuario/validar', ['as' => 'usuarios.validar', 'uses' => 'UsuarioController@validar']);
Route::get('usuario/logout', ['as' => 'usuario.logout', 'uses' => 'UsuarioController@logout']);
Route::resource('usuario', 'UsuarioController');
Route::resource('curriculum','CurriculumController');
Route::resource('ofertas', 'OfertasController');
Route::resource('experiencia','ExperienciaController');
Route::resource('formacion','FormacionController');
Route::resource('categoria','CategoriasController');
Route::get('grafico', ['as' => 'grafico.index', 'uses' => 'GraficoController@index']);
Route::get('empresa', ['as' => 'reporte.empresa', 'uses' => 'ReportesController@empresa']);
Route::get('vacantesCategoria', ['as' => 'reporte.vacantesCategoria', 'uses' => 'ReportesController@vacantesCategoria']);
Route::get('getEmpresas', ['as' => 'reporte.buscarEmpresa', 'uses' => 'ReportesController@buscarEmpresa']);
Route::get('mostrarEmpresa/{id}', ['as' => 'reporte.mostrarEmpresa', 'uses' => 'ReportesController@mostrarEmpresa']);
Route::get('getAplicadas', ['as' => 'reporte.ofertasAplicadas', 'uses' => 'ReportesController@ofertasAplicadas']);
Route::resource('postulaciones','PostulacionController');
Route::get('inicio', ['as' => 'categoria.inicio', 'uses' => 'CategoriasController@inicio']);
Route::get('aplicadas', ['as' => 'postulaciones.aplicadas', 'uses' => 'PostulacionController@aplicadas']);

Route::get('filtrar', ['as' => 'postulaciones.filtrar', 'uses' => 'PostulacionController@filtrar']);
Route::get('postulantes/{oferta}', ['as' => 'postulaciones.porOferta', 'uses' => 'PostulacionController@porOferta']);
Route::resource('requisito', 'RequisitoController');
//Route::get('requisito/{id}', ['as' => 'requisito.crear', 'uses' => 'RequisitoController@create']);

Proyecto2/app/Requisito.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Requisito extends Model
{
    protected $table = 'tbl_requisitos';
	protected $primaryKey = 'req_id';
	
	/**
	* @var array
    */
    protected $fillable = [
        'req_id', 'req_descripcion','ofer_id',
    ];
}

Proyecto2/app/Http/Controllers/RequisitoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Requisito;
use App\Http\Requests\RequisitoRequest;
use Illuminate\Support\Facades\DB;
use Session;

class RequisitoController extends Controller
{
    public function index(Request $id)
    {
        Session::put('oferta',$id->id);
        $req = Requisito::where('ofer_id',$id->id)->get();
        $ofer = DB::table('tbl_ofertas')->where('id',$id->id)->first();
        return view('requisitos.index', compact('req'),['ofer'=> $ofer]);
    }
    public function create( Request $id) 
    {
        $ofer = DB::table('tbl_ofertas')->where('id',$id->id)->first();
    	return view('requisitos.create',['ofer'=> $ofer->id]);
    }
    public function store(RequisitoRequest $request)
    {
    	$requisito = new Requisito;
    	$requisito->req_descripcion = $request->req_descripcion;
    	$requisito->ofer_id = $request->ofer_id;
    	$requisito->save();

        $req = Requisito::where('ofer_id',$request->ofer_id)->get();
        $ofer = DB::table('tbl_ofertas')->where('id',$request->ofer_id)->first();

        return view('requisitos.index', compact('req'),['ofer'=> $ofer]);
    }
    public function edit($id)
    {
    	$requisito = Requisito::find($id);

    	return view('requisitos.edit', compact('requisito'),['ofer'=> $requisito->ofer_id]);
    }
    public function update(RequisitoRequest $request, $id)
    {
    	$requisito = Requisito::find($id);
    	$requisito->req_descripcion = $request->req_descripcion;
    	$requisito->ofer_id = $request->ofer_id;
        $requisito->save();

        $req = Requisito::where('ofer_id',$request->ofer_id)->get();
        $ofer = DB::table('tbl_ofertas')->where('id',$request->ofer_id)->first();
        
        return view('requisitos.index', compact('req'),['ofer'=> $ofer]);
    }
    public function show($id)
    {
    	$requisitos = DB::table('tbl_requisitos')->where('ofer_id',$id)->get();
        $ofer = DB::table('tbl_ofertas')->where('id',$id)->first();
    	return view('requisitos.show', compact('requisitos'),['ofer'=> $ofer]);
    }
    public function destroy($id)  
    {
    	$requisito = Requisito::find($id);
    	$requisito->delete();
        $req = Requisito::where('ofer_id',$id)->get();
        $ofer = DB::table('tbl_ofertas')->where('id',Session::get('oferta'))->first();
        
        return view('requisitos.index', compact('req'),['ofer'=> $ofer]);
    }
}

Proyecto2/resources/views/requisitos/create.blade.php
@extends('layout')

@section('content')

<div class="column-sm-8">
	@include('curriculum.fragment.error')

	{!!Form::open(['route' => 'requisito.store'])!!}
	@include('requisitos.fragment.form')
	{!!Form::close() !!}
	</div>
@endsection

Proyecto2/resources/views/requisitos/edit.blade.php
@extends('layout')

@section('content')

<div class="column-sm-12">
	<h2>Editar Requisito</h2>
	@include('experiencias.fragment.error')
	
	{!!Form::model($requisito, ['route' => ['requisito.update',$requisito->req_id], 'method' => 'PUT'])!!}
	@include('requisitos.fragment.form')
	{!!Form::close() !!}

	</div>

@endsection

Proyecto2/resources/views/requisitos/index.blade.php
@extends('layout')

@section('content')

	<div>
		<h2>Requisitos
			<a href="{{ route('requisito.create',['id'=>$ofer->id])}}" class="btn btn-dark">Agregar</a>
			<a href="{{ route('ofertas.index')}}" class="btn btn-dark">Ofertas laborales</a>
		</h2>
		<br>
		<p><strong>Oferta Laboral</strong></p>
		<br>
		<table class="table">
			<tr><th>Descripcion de la oferta</th></tr>
			<tbody>
				<tr>
					<td>{{$ofer->ofer_descripcion}}</td>
				</tr>
			</tbody>
		</table>

		<table class="table">
			<tr><th>Descripcion del requisito</th></tr>
			<tbody>
				@foreach($req as $r)
				<tr>
					<td>{{$r->req_descripcion}}</td>
					<td><a href="{{ route('requisito.edit', $r->req_id)}}" class="btn btn-link">Editar</a></td>
					<td>
						<form action="{{ route('requisito.destroy', $r->req_id) }}" method="post"> 
							{{csrf_field()}}
							<input type="hidden" name="_method" value="DELETE">
							<button class="btn btn-link"> Eliminar</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>

@endsection

Proyecto2/resources/views/requisitos/show.blade.php
@extends('layout')

@section('content')

<div class="column-sm-8" >
	<h2>Requisitos</h2>
	<table class="table">
		<tr><th>Descripcion del requisito</th></tr>
		<tbody>
			@foreach($requisitos as $r)
			<tr>
				<td>{{$r->req_descripcion}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	<br>
	<table class="table">
		<tr><th>Categoria de la oferta</th><th>Descripcion de la oferta</th><th>Vacantes de la oferta</th><th>Fecha de la oferta</th></tr>
		<tbody>
			<tr>
				<td>{{$ofer->ofer_categoria}}</td>
				<td>{{$ofer->ofer_descripcion}}</td>
				<td>{{$ofer->ofer_vacantes}}</td>
				<td>{{$ofer->ofer_fecha}}</td>
			</tr>
		</tbody>
	</table>


</div>

@endsection