Proyecto2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () 
{
    return view('login');
});

Route::get('usuario/validar', ['as' => 'usuarios.validar', 'uses' => 'UsuarioController@validar']);
Route::get('usuario/logout', ['as' => 'usuario.logout', 'uses' => 'UsuarioController@logout']);
Route::resource('usuario', 'UsuarioController');
Route::resource('curriculum','CurriculumController');
Route::resource('ofertas', 'OfertasController');
Route::resource('experiencia','ExperienciaController');
Route::resource('formacion','FormacionController');
Route::resource('categoria','CategoriasController');
Route::get('grafico', ['as' => 'grafico.index', 'uses' => 'GraficoController@index']);
Route::get('empresa', ['as' => 'reporte.empresa', 'uses' => 'ReportesController@empresa']);
Route::get('vacantesCategoria', ['as' => 'reporte.vacantesCategoria', 'uses' => 'ReportesController@vacantesCategoria']);
Route::get('getEmpresas', ['as' => 'reporte.buscarEmpresa', 'uses' => 'ReportesController@buscarEmpresa']);
Route::get('mostrarEmpresa/{id}', ['as' => 'reporte.mostrarEmpresa', 'uses' => 'ReportesController@mostrarEmpresa']);
Route::get('getAplicadas', ['as' => 'reporte.ofertasAplicadas', 'uses' => 'ReportesController@ofertasAplicadas']);
Route::resource('postulaciones','PostulacionController');
Route::get('inicio', ['as' => 'categoria.inicio', 'uses' => 'CategoriasController@inicio']);
Route::get('aplicadas', ['as' => 'postulaciones.aplicadas', 'uses' => 'PostulacionController@aplicadas']);

Route::get('filtrar', ['as' => 'postulaciones.filtrar', 'uses' => 'PostulacionController@filtrar']);
Route::get('postulantes/{oferta}', ['as' => 'postulaciones.porOferta', 'uses' => 'PostulacionController@porOferta']);
Route::resource('requisito', 'RequisitoController');
//Route::get('requisito/{id}', ['as' => 'requisito.crear', 'uses' => 'RequisitoController@create']);

Proyecto2/resources/views/postulaciones/aplicadas.blade.php
@extends('layout')

@section('content')
		<div class="row">
			<div class="col-sm-12">
				<h1 class="text-center page-header">Ofertas laborales Aplicadas</h1>
				<a href="{{ route('postulaciones.index')}}" class="btn btn-outline-dark">Listar disponibles</a>
			</div>
            <br>
		</div>
		<div>
		@include('postulaciones.fragment.error')
		@include('postulaciones.fragment.info')
		</div>
        <br>
		<table class="table table-hover table-dark">
		<thead>
		<tr>	
				<th>Vacantes</th>
				<th>Fecha</th>
				<th>Descripcion</th>
				<th>Empresa</th>
				<th collapse="3">&nbsp;</th>
		</tr>		
		</thead>
		<tbody>
		@foreach( $ofertas as $oferta)
		<tr>
			<td> {{ $oferta->ofer_vacantes}}</td>
			<td>{{ $oferta->ofer_fecha }} </td>
			<td> {{ $oferta->ofer_descripcion}}</td>
			<td> {{ $oferta->usu_nombre}}</td>
			<td><form action="{{ route('postulaciones.destroy', $oferta->id) }}" method="post"> 
					{{csrf_field()}}
					<input type="hidden" name="_method" value="DELETE">
					<button class="btn btn-light"> Eliminar</button>
				</form> </td>
		</tr>
		@endforeach
		</tbody>
	</table>
@endsection

Proyecto2/resources/views/postulaciones/candidatos.blade.php
@extends('layout')

@section('content')
		<div class="row">
			<div class="col-sm-12">
				<h1 class="text-center page-header">Candidatos</h1>
				<a href="{{route('ofertas.index')}}" class="btn btn-outline-dark">Listar ofertas</a>
                <br>
			</div>
		</div>

		<div>
		@include('postulaciones.fragment.info')
		</div>
		<table class="table table-hover table-dark">
		<thead>
		<tr>	
				<th>Nombre</th>
				<th>Apellido</th>
				<th>Correo</th>
				<th collapse="3">&nbsp;</th>
		</tr>		
		</thead>
		<tbody>
		@foreach( $Usuarios as $usu)
		<tr>
			<td> {{ $usu->usu_nombre}}</td>
			<td> {{ $usu->usu_apellidos}} </td>
			<td> {{ $usu->usu_email}}</td>
			<td><a href="{{route('curriculum.show', $usu->usu_id)}}" class="btn btn-light">Curriculum</a></td>
			<td><a href="{{route('usuario.show', $usu->usu_id)}}" class="btn btn-light">Información</a></td>
		</tr>
		@endforeach
		</tbody>
	</table>
@endsection

Proyecto2/resources/views/postulaciones/index.blade.php
@extends('layout')

@section('content')
		<div class="row">
			<div class="col-sm-12">
				<h1 class="text-center page-header">Ofertas laborales disponibles</h1>
				<!--<a href="{{ route('ofertas.create')}}" class="btn btn-primary">Nueva</a>-->
				<a href="{{ route('postulaciones.aplicadas')}}" class="btn btn-outline-dark">Aplicadas</a>
                <br>
				<form action="{{ route('postulaciones.filtrar') }}" method="GET"> 
                    <div style="display: -webkit-box;">
                        <input type="text" class="form-control" name="valor" placeholder="Empresa o categoria">
                        <button class="btn btn-info"> BUSCAR</button>
                    </div>
				</form>
			</div>
		</div>

		<div>
		@include('postulaciones.fragment.info')
		</div>
		<table class="table table-hover table-dark">
		<thead>
		<tr>	
				<th>Vacantes</th>
				<th>Fecha</th>
				<th>Descripcion</th>
				<th>Empresa</th>
				<th collapse="3">&nbsp;</th>
		</tr>		
		</thead>
		<tbody>
		@foreach( $ofertas as $oferta)
		<tr>
			<td> {{ $oferta->ofer_vacantes}}</td>
			<td>{{ $oferta->ofer_fecha }} </td>
			<td> {{ $oferta->ofer_descripcion}}</td>
			<td> {{ $oferta->usu_nombre}}</td>
			
			<td><a href="{{ route('postulaciones.show', $oferta->id)}}" class="btn btn-light">Ver</a></td>
			<td><a href="{{ route('postulaciones.edit', $oferta->id)}}" class="btn btn-light">Aplicar a Oferta</a></td>
		</tr>
		@endforeach
		</tbody>
	</table>
@endsection

Proyecto2/resources/views/postulaciones/show.blade.php
@extends('layout')

@section('content')

<div class="column-sm-8" >
<a href="{{ route('postulaciones.edit', $oferta->id)}}" class="btn btn-dark">Aplicar a Oferta</a>
	<a href="{{route('postulaciones.index')}}" class="btn btn-dark">Listar ofertas Disponibles</a>
	<h2>{{$usuario->usu_nombre}}</h2>

<p><h5>Descripcion:</h5>
	{{$oferta->ofer_descripcion}} 
</p>

<p>
	<h5>Categoria:</h5>
	{{$categorias->cat_nombre}}
<p>

</p>
	<h5>Numero de vacantes</h5>
	{{$oferta->ofer_vacantes}}
</p>

<p>
	<h5>Fecha de oferta</h5>
	{{$oferta->ofer_fecha}}
</p>

<p>
	<h5>Contrato</h5>
	{{$oferta->ofer_contrato}}
</p>

<p>
	<h5>Dias laborados:</h5>
	{{$oferta->ofer_dia_inicio}}</br>
	{{$oferta->ofer_dia_fin}}</br>
	<h5>Horario:</h5>
	Inicio: {{$oferta->ofer_hora_inicio}}</br>
	Salida: {{$oferta->ofer_hora_fin}}</br>
</p>
</div>


@endsection